const ScreenNames = {
  SplashScreen: 'hpo.splash',
  LoginScreen: 'hpo.login',
  PinScreen: 'hpo.pin',
  AppointmentScreen: 'hpo.appointment',
  ReportsScreen: 'hpo.reports',
  CustomersScreen: 'hpo.customers',
  CustomerNewScreen: 'hpo.customers.new',
  CustomerDetailScreen: 'hpo.customers.detail',
  MoreScreen: 'hpo.more',
  AppointmentsPage: 'hpo.appointment.list',
  SchedulePage: 'hpo.appointment.schedule',
  AppointmentDetailScreen: 'hpo.appointment.detail',
  AppointmentNewScreen: 'hpo.appointment.new',
  CustomerListPage: 'hpo.appointment.new.customerList',
  BookingPage: 'hpo.appointment.new.booking',
  SelectDatePage: 'hpo.appointment.new.booking.selectDate',
  SelectServicePage: 'hpo.appointment.new.booking.selectService',
  ReviewPage: 'hpo.appointment.new.booking.review',
  ServiceScreen : 'hpo.service',
  ServiceNewScreen : 'hpo.service.new',
  CategoryNewScreen : 'hpo.category.new',
  EditProfileScreen : 'hpo.profile.edit',
  SettingScreen : 'hpo.setting',
  NotificationScreen : 'hpo.notification',
  ReviewScreen : 'hpo.review',
  MarketingScreen : 'hpo.marketing',
  MarketingNewScreen : 'hpo.marketing.new',
  Campaigns : 'hpo.campaigns',
  MarketPlace : 'hpo.marketplace',
  CheckoutScreen : 'hpo.checkout',
  SelectService : 'hpo.appointment.booking.selectService',
  SelectServiceDetail : 'hpo.appointment.booking.selectService.detail',
  SelectStaff : 'hpo.appointment.booking.selectStaff',
  SelectDateTime : 'hpo.appointment.booking.selectDateTime',
  ReviewConfirm : 'hpo.appointment.booking.reviewConfirm',
  ExtraScreen : 'hpo.extra',
  ExtraNewScreen : 'hpo.extra.new',
  ProductScreen : 'hpo.product',
  ProductNewScreen : 'hpo.product.new',
  StaffScreen : 'hpo.staff',
  StaffNewScreen : 'hpo.staff.new',

};

module.exports = { ScreenNames };
