export const images = {
  logo: require('@src/assets/images/logo.png'),
  serviceDefault: require('@src/assets/images/serviceDefault.png'),
  productDefault: require('@src/assets/images/productDefault.png'),
  iconSignIn: require('@src/assets/images/icon_signin.png'),
  iconTabAppointment: require('@src/assets/images/icon_tab_appointment.png'),
  iconTabReports: require('@src/assets/images/icon_tab_reports.png'),
  iconTabCustomer: require('@src/assets/images/icon_tab_customers.png'),
  iconTabMore: require('@src/assets/images/icon_tab_more.png'),
  imageHeaderBg: require('@src/assets/images/header_bg.png'),
  imageAvatarDefault: require('@src/assets/images/image_avatar_default.png'),
  iconMailBox: require('@src/assets/images/icon_mail_box.png'),
  iconBell: require('@src/assets/images/icon_bell.png'),
  iconDate: require('@src/assets/images/icon_date.png'),
  iconSchedule: require('@src/assets/images/icon_schedule.png'),
  iconBack: require('@src/assets/images/back.png'),
  iconMore: require('@src/assets/images/more.png'),
  iconArrow: require('@src/assets/images/arrow.png'),
  iconAtHome: require('@src/assets/images/mask_group_116.png'),
  iconClose: require('@src/assets/home/icon_close.png'),
  iconCloseGrey: require('@src/assets/home/icon_close_grey.png'),
  iconSearchBlue: require('@src/assets/home/icon_search_blue.png'),
  iconAdd: require('@src/assets/home/add_icon.png'),
  iconCalendar: require('@src/assets/images/iconCalendar.png'),
  iconClock: require('@src/assets/images/iconClock.png'),
  iconPlus: require('@src/assets/images/iconPlus.png'),
  iconUpload: require('@src/assets/home/icon_addImage.png'),

  EmptyList: require('@src/assets/images/emptyList.png'),
  barTimeLine: require('@src/assets/images/barTimeLine.png'),
  dropdown : require('@src/assets/images/dropdown.png'),
  buttonPlus : require('@src/assets/home/button_plus.png'),
  arrowRight: require('@src/assets/images/arrowRight.png'),
  treedot: require('@src/assets/home/treedot.png'),
};

export const svg = {
  logo_fade: require('@src/assets/svg/logo_fade.json'),
};
