export const images = {
  logo: require('@src/assets/images/logo.png'),
  serviceDefault: require('@src/assets/images/serviceDefault.png'),
  productDefault: require('@src/assets/images/productDefault.png'),
  iconSignIn: require('@src/assets/images/icon_signin.png'),
  iconTabAppointment: require('@src/assets/images/icon_tab_appointment.png'),
  iconTabReports: require('@src/assets/images/icon_tab_reports.png'),
  iconTabCustomer: require('@src/assets/images/icon_tab_customers.png'),
  iconTabMore: require('@src/assets/images/icon_tab_more.png'),
  imageHeaderBg: require('@src/assets/images/header_bg.png'),
  imageAvatarDefault: require('@src/assets/images/image_avatar_default.png'),
  iconMailBox: require('@src/assets/images/icon_mail_box.png'),
  iconBell: require('@src/assets/images/icon_bell.png'),
  iconDate: require('@src/assets/images/icon_date.png'),
  iconSchedule: require('@src/assets/images/icon_schedule.png'),
  iconBack: require('@src/assets/images/back.png'),
  iconMore: require('@src/assets/images/more.png'),
  iconArrow: require('@src/assets/images/arrow.png'),
  iconAtHome: require('@src/assets/images/mask_group_116.png'),
  iconClose: require('@src/assets/home/icon_close.png'),
  iconCloseGrey: require('@src/assets/home/icon_close_grey.png'),
  iconSearchBlue: require('@src/assets/home/icon_search_blue.png'),
  iconAdd: require('@src/assets/home/add_icon.png'),
  iconCalendar: require('@src/assets/images/iconCalendar.png'),
  iconClock: require('@src/assets/images/iconClock.png'),
  iconPlus: require('@src/assets/images/iconPlus.png'),
  iconSales: require('@src/assets/images/iconSales.png'),
  iconService: require('@src/assets/images/iconService.png'),
  iconMarketing: require('@src/assets/images/iconMarketing.png'),
  iconPayment: require('@src/assets/images/iconPayment.png'),
  iconSetting: require('@src/assets/images/iconSetting.png'),
  iconReview: require('@src/assets/images/iconReview.png'),
  iconHardware: require('@src/assets/images/iconHardware.png'),
  iconInvoice: require('@src/assets/images/iconInvoice.png'),
  iconBusiness: require('@src/assets/images/iconBusiness.png'),
  iconNote: require('@src/assets/images/iconNote.png'),
  iconPhone: require('@src/assets/images/iconPhone.png'),
  iconEmail: require('@src/assets/images/iconEmail.png'),
  icon_email : require('@src/assets/images/icon_email.png'),
  iconGender: require('@src/assets/images/iconGender.png'),
  iconBirthdate: require('@src/assets/images/iconBirthdate.png'),
  iconLocation: require('@src/assets/images/iconLocation.png'),
  iconReferer: require('@src/assets/images/iconReferer.png'),
  iconVip: require('@src/assets/images/vip_icon.png'),
  iconCamera: require('@src/assets/images/icon_camera.png'),
  iconUpload: require('@src/assets/home/icon_addImage.png'),
  iconFilter: require('@src/assets/images/iconFilter.png'),
  iconStar: require('@src/assets/images/iconStar.png'),
  iconStarHalf: require('@src/assets/images/iconStarHalf.png'),
  iconSync: require('@src/assets/images/sync.png'),
  iconPayment: require('@src/assets/images/Payment.png'),
  fullStar: require('@src/assets/images/fullstar.png'),
  halfStar: require('@src/assets/images/halfStar.png'),
  iconNotFound: require('@src/assets/images/iconNotFound.png'),
  circleGreen: require('@src/assets/images/circleGreen.png'),
  circleGrey: require('@src/assets/images/circleGrey.png'),
  checkout_customer_icon: require('@src/assets/images/checkout_customer_icon.png'),
  plus: require('@src/assets/images/plusIcon.png'),
  iconExtra: require('@src/assets/images/iconExtra.png'),
  iconChangeDate: require('@src/assets/images/iconChangeDate.png'),
  iconAddMore: require('@src/assets/images/iconAddMore.png'),
  iconAddNote: require('@src/assets/images/iconAddNote.png'),
  iconTrash: require('@src/assets/images/trash.png'),
  iconChecked: require('@src/assets/images/iconChecked.png'),
  iconCloseSettlement: require('@src/assets/images/iconCloseSettlement.png'),
  iconInventory: require('@src/assets/images/iconInventory.png'),
  staff_default: require('@src/assets/images/staff_default.png'),
  iconExport: require('@src/assets/images/export.png'),
  iconStaff: require('@src/assets/images/iconStaff.png'),
  iconEditPencil: require('@src/assets/images/create-24px.png'),
  iconEye: require('@src/assets/images/eye.png'),
  iconTrash: require('@src/assets/images/trash.png'),
  iconHidden: require('@src/assets/images/hidden.png'),
  schedule_checkinAppointment: require('@src/assets/images/schedule_checkinAppointment.png'),
  schedule_confirmAppointment: require('@src/assets/images/schedule_confirmAppointment.png'),
  schedule_deleteAppointment: require('@src/assets/images/schedule_deleteAppointment.png'),
  schedule_newAppointment: require('@src/assets/images/schedule_newAppointment.png'),
  schedule_updateAppointment: require('@src/assets/images/schedule_updateAppointment.png'),
  clear_all: require('@src/assets/images/clear_all.png'),
  penEdit: require('@src/assets/images/penEdit.png'),
  checked_success: require('@src/assets/images/checked_success.png'),
  harmonyPay: require('@src/assets/images/harmonyPay.png'),
  creditCardPay: require('@src/assets/images/credit_payment.png'),
  debitCardPay: require('@src/assets/images/debitCardPay.png'),
  cashPay: require('@src/assets/images/cashPay.png'),
  otherPay: require('@src/assets/images/otherPay.png'),
  giftCardPay: require('@src/assets/images/giftcard_payment.png'),
  downarrow: require('@src/assets/images/down-arrow.png'),
  iconLoading: require('@src/assets/images/Loading.gif'),
  scancode: require('@src/assets/images/scancode.png'),
  date_range: require('@src/assets/images/date_range.png'),
  iconCalendar2: require('@src/assets/images/iconCalendar2.png'),
  iconPrint: require('@src/assets/images/print.png'),
  iconShare: require('@src/assets/images/share_icon.png'),
  iconFilter: require('@src/assets/images/filter.png'),
  iconMarketingGrey: require('@src/assets/images/iconMarketingGrey.png'),
  iconPen: require('@src/assets/images/iconPen.png'),
  iconSettlement: require('@src/assets/images/iconSettlement.png'),
  iconReportStaff: require('@src/assets/images/iconReportStaff.png'),
  iconReportCustomer: require('@src/assets/images/iconReportCustomer.png'),
  iconReportOverall: require('@src/assets/images/iconReportOverall.png'),
  iconReportService: require('@src/assets/images/iconReportService.png'),
  iconReportGiftcard: require('@src/assets/images/iconReportGiftcard.png'),
  iconReportProduct: require('@src/assets/images/iconReportProduct.png'),
  sortDown: require('@src/assets/images/down.png'),
  sortUp: require('@src/assets/images/up.png'),
  sortNone: require('@src/assets/images/sort_none.png'),
  emoji1 :  require('@src/assets/images/emoji1.png'),
  emoji2 :  require('@src/assets/images/emoji2.png'),
  emoji3 :  require('@src/assets/images/emoji3.png'),
  emoji4 :  require('@src/assets/images/emoji4.png'),
  emoji5 :  require('@src/assets/images/emoji5.png'),
  emoji_1 :  require('@src/assets/images/emoji_1.png'),
  emoji_2 :  require('@src/assets/images/emoji_2.png'),
  emoji_3 :  require('@src/assets/images/emoji_3.png'),
  emoji_4 :  require('@src/assets/images/emoji_4.png'),
  emoji_5 :  require('@src/assets/images/emoji_5.png'),

  visaLogo : require('@src/assets/images/visaLogo.png'),
  masterCardLogo : require('@src/assets/images/masterCardLogo.png'),
  discoverLogo : require('@src/assets/images/discoverLogo.png'),
  other_card : require('@src/assets/images/other_card.png'),
  american_express : require('@src/assets/images/american_express.png'),

  EmptyList: require('@src/assets/images/emptyList.png'),
  barTimeLine: require('@src/assets/images/barTimeLine.png'),
  dropdown: require('@src/assets/images/dropdown.png'),
  buttonPlus: require('@src/assets/home/button_plus.png'),
  arrowRight: require('@src/assets/images/arrowRight.png'),
  treedot: require('@src/assets/home/treedot.png'),
  danger: require('@src/assets/images/danger.png'),
  checkBox: require('@src/assets/images/check-box.png'),
  checkBoxEmpty: require('@src/assets/images/check-box-empty.png'),
};

export const svg = {
  logo_fade: require('@src/assets/svg/logo_fade.json'),
};
